FROM python:3.11-slim-bullseye AS python-builder
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /botamusique
RUN apt-get update \
    && apt-get install --no-install-recommends -y gcc g++ ffmpeg libjpeg-dev libmagic-dev opus-tools zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*
COPY . /botamusique
RUN python3 -m venv venv \
    && venv/bin/pip install wheel \
    && venv/bin/pip install -r requirements.txt


FROM node:16-bullseye-slim AS node-builder
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /botamusique/web
COPY web /botamusique/web
RUN npm install
RUN npm run build


FROM python:3.11-slim-bullseye AS template-builder
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /botamusique
COPY --from=python-builder /botamusique .
COPY --from=node-builder /botamusique/web/templates web/templates
COPY --from=node-builder /botamusique/static static
RUN venv/bin/python scripts/translate_templates.py --lang-dir /botamusique/lang --template-dir /botamusique/web/templates


FROM python:3.11-slim-bullseye
ENV DEBIAN_FRONTEND=noninteractive
EXPOSE 8181
WORKDIR /botamusique
RUN apt-get update \
    && apt-get install --no-install-recommends -y opus-tools ffmpeg libmagic-dev curl tar zlib1g \
    && rm -rf /var/lib/apt/lists/*
COPY --from=python-builder /botamusique .
COPY --from=template-builder /botamusique/static static
COPY --from=template-builder /botamusique/web/templates web/templates
# 转换 entrypoint.sh 换行符（Windows 打包的源码可能是 CRLF）
RUN sed -i 's/\r$//' entrypoint.sh && chmod +x entrypoint.sh
ENTRYPOINT [ "/botamusique/entrypoint.sh" ]
CMD ["venv/bin/python", "mumbleBot.py"]
