[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[program:netease-api]
command=node app.js
directory=/netease-api
autostart=true
autorestart=true
startretries=5
startsecs=2
stderr_logfile=/var/log/supervisor/netease-api.err.log
stdout_logfile=/var/log/supervisor/netease-api.out.log

[program:botamusique]
command=/botamusique/entrypoint.sh venv/bin/python mumbleBot.py
directory=/botamusique
autostart=true
autorestart=true
startretries=5
startsecs=2
stderr_logfile=/var/log/supervisor/botamusique.err.log
stdout_logfile=/var/log/supervisor/botamusique.out.log
